README.md

I noticed a typo in the README. That's all.

Fix typo in README: added (was: addded)

---

DEVELOPMENT.md

It takes me a while to try this list out and finally makes the project running on my local machine, thought it may save other people's time to list it here.

Add DEVELOPMENT.md

---

saythanks/static/css/saythanks.css
saythanks/templates/index.htm.j2

The register buttons dropped before mobile. I added a media query to neaten up the buttons and the "or".

fixed register buttons on mobile and centered section

---

saythanks/templates/base.htm.j2

I tried figuring out how to get a date in Jinja2 without an extra dependency (or any backend changes, since I don't have the API keys to run the app locally), but no dice, so I'm submitting a hardcoded version at least.

Update copyright year

---

README.md
saythanks/core.py

Updates to use OAuth2 and hide email address on the links to the inbox

changed colour of button

---

saythanks/core.py

Resolve #39.

---

saythanks/templates/base.htm.j2

add new issue link in footer

---

saythanks/core.py
saythanks/static/css/carbonads.css
saythanks/static/index.html
saythanks/templates/base.htm.j2
saythanks/templates/inbox.htm.j2
saythanks/templates/index.htm.j2
saythanks/templates/thanks.htm.j2

Changes for Bitcoin, Buysellads and QR Code

Changes for Bitcoin, Buysellads and QR Code

---

saythanks/templates/submit_note.htm.j2

Reverts BlitzKraft/saythanks.io#133

Revert "Update submit_note.htm.j2"

---

saythanks/static/js/jquery.simplyCountable.js
saythanks/static/js/main.js

for issue #143 
deleted braces and divided the expression into two statements.

modified unused expressions for #143

---

saythanks/core.py
saythanks/templates/submit_note.htm.j2

@BlitzKraft : Here is my solution to the #58 feature request I raised. Please take a look. Also since we do not have any contribution guide, I am not sure of any tests that needs to be run.

[#58] Add topic attribution to saythanks link.

---

saythanks/storage.py

- Defining the uuid variable already in the init function of the corresponding class to improve readabilty.
- Closes #155

Define self.uuid in init

---

saythanks/core.py

Fixed #160 as reviewed by Pavithra 

---

saythanks/templates/submit_note.htm.j2

added right arrow key shortcut to auto-fill placeholder text into text-area.

Completed feature no.1 from issue #162

---

saythanks/static/css/saythanks.css
saythanks/storage.py
saythanks/templates/base.htm.j2
saythanks/templates/inbox.htm.j2

Exact exception has been captured and thrown - Fixed - #168

Exact exception has been captured and thrown

---

saythanks/templates/base.htm.j2
saythanks/templates/inbox.htm.j2
saythanks/templates/submit_note.htm.j2

Fixed Font menu bugs and added the menu to sendnote

---

saythanks/core.py

Bug Fix on Topic feature implementation

---

saythanks/templates/submit_note.htm.j2

fixed issue #162 with bug fixes

---

saythanks/storage.py

Unique Violation handled for auth id 

---

saythanks/storage.py

Handled Index error to check at least one entry exist for authenticated login

---

saythanks/storage.py
saythanks/templates/base.htm.j2
saythanks/templates/inbox.htm.j2

Added timestamp in inbox for each notes

---

saythanks/templates/base.htm.j2
saythanks/templates/inbox.htm.j2

Link to send to Twitter and Facebook from saythanks.io-fixed #171

---

saythanks/core.py
saythanks/myemail.py
saythanks/templates/submit_note.htm.j2

Added HTML email option

---

saythanks/core.py
saythanks/templates/base.htm.j2
saythanks/templates/inbox.htm.j2

all the issues are fixed related to #171

---

.github/ISSUE_TEMPLATE/---technical-issue.md
.github/ISSUE_TEMPLATE/--bug-report.md
.github/ISSUE_TEMPLATE/--new-feature.md

Added issue templates

---

saythanks/templates/inbox.htm.j2

removed strong tags from byline and timestamp

---

.gitignore
saythanks/core.py
saythanks/myemail.py
saythanks/storage.py

Log module added
Fixed #IssueNumber

Log module added

---

saythanks/static/css/saythanks.css
saythanks/templates/base.htm.j2

Ribbon Mobile View Issue #119

---

saythanks/core.py

Outside scope smothering avoided by using ibox

---

docs/saythanks_development.md

Specify maximum python version in docs

---

saythanks/templates/thanks.htm.j2

Fixed #234 
Missed to update the script's version here!
@Pavithratrdev, @kgashok please let me know about this update.

Bump auth0 lock script version to 11.33 in /thanks template

---

requirements.txt
saythanks/storage.py

Fixed #245 
@Pavithratrdev, @kgashok please let me know about this update.

Migrate from records to SQLalchemy to handle DB operations

---

saythanks/templates/submit_note.htm.j2

Fixed #183 
@Pavithratrdev @kgashok , please let me know about this update.

Add simpleMDE as md editor in submit note

---

docs/saythanks_development.md
saythanks/templates/submit_note.htm.j2

Fixed #183 
@Pavithratrdev @kgashok , please let me know about this update.

Editor fix

---

saythanks/core.py
saythanks/static/css/normalize.css
saythanks/static/css/saythanks.css
saythanks/static/css/skeleton.css
saythanks/templates/inbox.htm.j2
saythanks/templates/submit_note.htm.j2

Fixed #212 
@Pavithratrdev @kgashok please let me know about this update.

Updates to Inbox

---

Pipfile
Pipfile.lock
saythanks/core.py

@Pavithratrdev, @kgashok please let me know about this update.

Add markdown to pipfile and remove print statements

---

saythanks/sqls/schema.sql

Sql query update FIXES #267

---

requirements.txt
saythanks/core.py
saythanks/static/css/saythanks.css
saythanks/static/css/skeleton.css
saythanks/storage.py
saythanks/templates/404notfound.htm.j2
saythanks/templates/inbox.htm.j2
saythanks/templates/share_note.htm.j2

for issue #272 
and the following sub issues- #273 #276  #277  #278 
I @Adithya14255 and @marudhu2004 have done the following:
[x] added the issue number for which this pull request is created.
[x] added pagination for inbox
[x] ensured that search feature works with the new changes
[x] handled bad requests which might come with page count (negative pages, above page limit) by returning 404
[x] added custom 404 page
futher by @Adithya14255
[x] pagination with search
[x] clear button to remove searched string
[x] fixed some issues with using same route for both search and normal
[x] fixed some session problems
[x] page change only visible when more than 1 page exists
[x] fixed issue when new login leads to error page
Further for issue #276 
[x] spacing has been added as shown - 
[x] The …

Final pagination

---

saythanks/myemail.py
saythanks/storage.py

Fixed #285 
@Srimathij and @Pavithratrdev, please let me know about this update.

Refactored the code for including public URL in the email notification

---

saythanks/myemail.py
saythanks/storage.py

Added one more link which is humanly readable and immediately copy-able. 

---

saythanks/myemail.py

The base_url problem has been fixed using the request function in flask 

---

saythanks/templates/submit_note.htm.j2

Fix for #281 and sub-issue #302

---

saythanks/templates/submit_note.htm.j2

Buttons now provide for some cookie-cutter sample messages. 

---

saythanks/templates/inbox.htm.j2

Fixed #286 
@kgashok  @Pavithratrdev, please let me know about this update.

Enhancement: Implement dynamic "Load More" button to append inbox messages

---

saythanks/storage.py

Merged two queries into one for search_notes, and filtered out archived notes

---

saythanks/static/manifest.json
saythanks/templates/base.htm.j2

added manifest.json for #321

---

saythanks/templates/inbox.htm.j2

Fixed #286 
@kgashok  @Pavithratrdev, please let me know about this update.

Enhancement: Add a dynamic "Load More" button to load inbox messages without page reloads, alongside the existing pagination

---

saythanks/static/manifest.json

removed theme colour to fix #322

---

saythanks/templates/base.htm.j2
saythanks/templates/submit_note.htm.j2

Enabled topic to be available as default in the message

---

README.md
saythanks/core.py
saythanks/myemail.py
saythanks/storage.py
saythanks/templates/submit_note.htm.j2

Now Subject in email contains topic as well

---

saythanks/templates/submit_note.htm.j2

Email delivery fails if no topic is mentioned

---

saythanks/core.py
saythanks/myemail.py
saythanks/templates/submit_note.htm.j2

Fixed #345, #346, #347, #348, #349

Multiple fixes for resolving proper email content formatting

---

saythanks/core.py
saythanks/myemail.py
saythanks/storage.py
saythanks/templates/submit_note.htm.j2

Fixed #287 
@kgashok  @Pavithratrdev, please let me know about this update.

Fixed #287

---

saythanks/storage.py

Partial fixes for #287 when no "audio_path" column is not available in the user's DB

---

saythanks/core.py

Fixed #366

---

saythanks/core.py

Fixed #361 
@kgashok  @Pavithratrdev, please let me know about this update.

Fix CSV export : Resolved the issue where exporting data to CSV was failing. 

---

saythanks/core.py
saythanks/myemail.py
saythanks/storage.py
saythanks/templates/inbox.htm.j2

Fixed #374, #55 (duplicate of #361)

Miscellaneous code changes

---

saythanks/core.py
saythanks/myemail.py
saythanks/storage.py

Fixed #372

---

saythanks/templates/inbox.htm.j2

Added changes to inbox.htm.j2 that got missed out
